# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Weather.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WeatherInformationSystem(object):
    def setupUi(self, WeatherInformationSystem):
        WeatherInformationSystem.setObjectName("WeatherInformationSystem")
        WeatherInformationSystem.resize(608, 692)
        WeatherInformationSystem.setAcceptDrops(True)
        WeatherInformationSystem.setAutoFillBackground(False)
        WeatherInformationSystem.setStyleSheet("QWidget{background-color: #20AAF9;}\n"
"QPushButton{\n"
"background-color: #CCCCCC;\n"
"font-size: 19px;\n"
"border: 2px solid black;    \n"
"}\n"
"QListWidget{\n"
"background-color: #CCCCCC;\n"
"font-size: 19px;    \n"
"border: 2px solid black;\n"
"}\n"
"QLabel{\n"
"background-color: #CCCCCC;\n"
"font-size: 19px;    \n"
"border: 2px solid black;\n"
"}\n"
"QCheckBox{\n"
"background-color: #CCCCCC;\n"
"font-size: 19px;    \n"
"border: 2px solid black;\n"
"}\n"
"QSlider{\n"
"background-color: #CCCCCC;\n"
"font-size: 19px;    \n"
"border: 2px solid black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(WeatherInformationSystem)
        self.centralwidget.setObjectName("centralwidget")
        self.weather_res = QtWidgets.QListWidget(self.centralwidget)
        self.weather_res.setGeometry(QtCore.QRect(10, 350, 591, 331))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.weather_res.setFont(font)
        self.weather_res.setStyleSheet("font: 18pt \"Arial\";")
        self.weather_res.setObjectName("weather_res")
        self.cityName = QtWidgets.QLineEdit(self.centralwidget)
        self.cityName.setGeometry(QtCore.QRect(10, 20, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cityName.setFont(font)
        self.cityName.setAutoFillBackground(False)
        self.cityName.setStyleSheet("background-color: rgb(186, 186, 186);\n"
"font: 22pt \"Arial\";")
        self.cityName.setText("")
        self.cityName.setObjectName("cityName")
        self.weatherButton = QtWidgets.QPushButton(self.centralwidget)
        self.weatherButton.setGeometry(QtCore.QRect(430, 20, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.weatherButton.setFont(font)
        self.weatherButton.setStyleSheet("font: 14pt \"Arial\";")
        self.weatherButton.setObjectName("weatherButton")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(480, 290, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.clearButton.setFont(font)
        self.clearButton.setStyleSheet("font: 14pt \"Arial\";")
        self.clearButton.setObjectName("clearButton")
        self.city_list = QtWidgets.QListWidget(self.centralwidget)
        self.city_list.setGeometry(QtCore.QRect(10, 91, 281, 251))
        self.city_list.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.city_list.setObjectName("city_list")
        self.days_list = QtWidgets.QListWidget(self.centralwidget)
        self.days_list.setGeometry(QtCore.QRect(300, 150, 171, 191))
        self.days_list.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.days_list.setObjectName("days_list")
        self.removeCity_Button = QtWidgets.QPushButton(self.centralwidget)
        self.removeCity_Button.setGeometry(QtCore.QRect(300, 90, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.removeCity_Button.setFont(font)
        self.removeCity_Button.setStyleSheet("font: 14pt \"Arial\";")
        self.removeCity_Button.setObjectName("removeCity_Button")
        WeatherInformationSystem.setCentralWidget(self.centralwidget)

        self.retranslateUi(WeatherInformationSystem)
        QtCore.QMetaObject.connectSlotsByName(WeatherInformationSystem)

    def retranslateUi(self, WeatherInformationSystem):
        _translate = QtCore.QCoreApplication.translate
        WeatherInformationSystem.setWindowTitle(_translate("WeatherInformationSystem", "WeatherInformationSystem"))
        self.cityName.setPlaceholderText(_translate("WeatherInformationSystem", "Input city name here"))
        self.weatherButton.setText(_translate("WeatherInformationSystem", "GetWeather"))
        self.clearButton.setText(_translate("WeatherInformationSystem", "Clear Res"))
        self.removeCity_Button.setText(_translate("WeatherInformationSystem", "Remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WeatherInformationSystem = QtWidgets.QMainWindow()
    ui = Ui_WeatherInformationSystem()
    ui.setupUi(WeatherInformationSystem)
    WeatherInformationSystem.show()
    sys.exit(app.exec_())
